FONT_FAMILY = "Arial"
FONT_SIZE_NORMAL = 11
FONT_SIZE_EDIT_SIZE = 12
FONT_SIZE_LARGE = 15
FONT_SIZE_EXTRA_LARGE = 50
FONT_WEIGHT_NORMAL = 50
FONT_WEIGHT_BOLD = 75

WINDOW_TITLE = "LgClientDisplay"
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 900
WINDOW_ICON_PATH = "./resources/gun.png"
WINDOW_ICON_SIZE = 50

MENUBAR_LEFT = 0
MENUBAR_TOP = 0
MENUBAR_WIDHT = 1400
MENUBAR_HEIGHT = 23
MENUBAR_OBJECT_NAME = "menubar"
MENUFILE_OBJECT_NAME = "menuFile"
MENUHELP_OBJECT_NAME = "menuHelp"
MENUFILE_TEXT = "File"
MENUHELP_TEXT = "Help"
MENUEXIT_TEXT = "Exit"
MENUABOUT_TEXT = "About"
MENUACONFIG_TEXT = "Pre-Arm Config"
ACTION_EXIT = "Exit"
ACTION_ABOUT = "About"
ACTION_CONFIG= "Config"

STATUS_BAR_OBJECT_NAME = "statusbar"

CENTRAL_OBJECT_NAME = "centralwidget"
CENTRAL_WIDGET_WIDTH = 1400
CENTRAL_WIDGET_HEIGHT = 870

# System State Panel
GROUPBOX_SYSTEM_STATE_TITLE = "System State"
GROUPBOX_SYSTEM_STATE_LEFT = 10
GROUPBOX_SYSTEM_STATE_TOP = 10
GROUPBOX_SYSTEM_STATE_WIDTH = 300
GROUPBOX_SYSTEM_STATE_HEIGHT = 55
GROUPBOX_SYSTEM_STATE_OBJECT_NAME = "groupBox_system_state"

NON_EDIT_TEXT_DEFAULT_TEXT = "Unknown"
NON_EDIT_TEXT_LEFT = 12
NON_EDIT_TEXT_TOP = 18
NON_EDIT_TEXT_WIDHT = 280
NON_EDIT_TEXT_HEIGHT = 30
NON_EDIT_TEXT_OBJECT_NAME = "nonEditText_system_state"

# Connection Panel
GROUPBOX_CONNECTION_TITLE = "Connection"
GROUPBOX_CONNECTION_LEFT = 10
GROUPBOX_CONNECTION_TOP = 68
GROUPBOX_CONNECTION_WIDTH = 300
GROUPBOX_CONNECTION_HEIGHT = 140
GROUPBOX_CONNECTION_OBJECT_NAME = "groupBox_connection"

BUTTON_CONNECTION_TITLE_CONNECT = "Connect"
BUTTON_CONNECTION_TITLE_DISCONNECT = "Disconnect"
BUTTON_CONNECTION_LEFT = 10
BUTTON_CONNECTION_TOP = 82
BUTTON_CONNECTION_WIDTH = 200
BUTTON_CONNECTION_HEIGHT = 45
BUTTON_CONNECTION_OBJECT_NAME = "pushButton_connection"

GROUPBOX_REMOTE_ADDRESS_TITLE = "Remote Address"
GROUPBOX_REMOTE_ADDRESS_LEFT = 10
GROUPBOX_REMOTE_ADDRESS_TOP = 20
GROUPBOX_REMOTE_ADDRESS_WIDTH = 280
GROUPBOX_REMOTE_ADDRESS_HEIGHT = 50
GROUPBOX_REMOTE_OBJECT_NAME = "groupBox_remote_address"

EDIT_TEXT_REMOTE_ADDRESS_DEFAULT_TEXT = "raspberrypi.local"
EDIT_TEXT_REMOTE_ADDRESS_LEFT = 10
EDIT_TEXT_REMOTE_ADDRESS_TOP = 15
EDIT_TEXT_REMOTE_ADDRESS_WIDTH = 260
EDIT_TEXT_REMOTE_ADDRESS_HEIGHT = 30
EDIT_TEXT_REMOTE_ADDRESS_OBJECT_NAME = "editText_remote_address"

CON_HORIZONTAL_LAYOUT_LEFT = 220
CON_HORIZONTAL_LAYOUT_TOP = 70
CON_HORIZONTAL_LAYOUT_WIDTH = 70
CON_HORIZONTAL_LAYOUT_HEIGHT = 70
CON_HORIZONTAL_LAYOUT_OBJECT_NAME = "horizontalLayoutWidget"
CONNECTION_LAYOUT_OBJECT_NAME = "connectionLayout"

GIF_LABEL_WIDTH = 55
GIF_LABEL_HEIGHT = 55
GIF_ICON_PATH = "./resources/search.gif"
GIF_LABEL_OBJECT_NAME = "gifLabel"
GIF_SPEED = 170
GIF_ICON_CONNECTED_PATH = "./resources/connected.gif"

# Control Mode Panel
GROUPBOX_CONTROL_PANEL_TITLE = "Mode Control"
GROUPBOX_CONTROL_PANEL_LEFT = 10
GROUPBOX_CONTROL_PANEL_TOP = 220
GROUPBOX_CONTROL_PANEL_WIDTH = 300
GROUPBOX_CONTROL_PANEL_HEIGHT = 230
GROUPBOX_MODE_CONTROL_PANEL_OBJECT_NAME = "groupBox_mode_control_panel"

BUTTON_SAFE_MODE_TITLE = "Safe Mode"
BUTTON_SAFE_MODE_LEFT = 10
BUTTON_SAFE_MODE_TOP = 25
BUTTON_SAFE_MODE_WIDTH = 280
BUTTON_SAFE_MODE_HEIGHT = 40
BUTTON_SAFE_MODE_OBJECT_NAME = "pushButton_safe_mode"

GROUPBOX_PRE_ARM_CODE_TITLE = "Pre-Arm Code"
GROUPBOX_PRE_ARM_CODE_LEFT = 10
GROUPBOX_PRE_ARM_CODE_TOP = 77
GROUPBOX_PRE_ARM_CODE_WIDTH = 190
GROUPBOX_PRE_ARM_CODE_HEIGHT = 50
GROUPBOX_PRE_ARM_CODE_OBJECT_NAME = "groupBox_pre_arm_code"

BUTTON_PRE_ARM_MODE_TITLE = "Pre Arm"
BUTTON_PRE_ARM_MODE_LEFT = 210
BUTTON_PRE_ARM_MODE_TOP = 85
BUTTON_PRE_ARM_MODE_WIDTH = 80
BUTTON_PRE_ARM_MODE_HEIGHT = 40
BUTTON_PRE_ARM_MODE_OBJECT_NAME = "pushButton_pre_arm_mode"

EDIT_TEXT_PRE_ARM_LEFT = 10
EDIT_TEXT_PRE_ARM_TOP = 15
EDIT_TEXT_PRE_ARM_WIDTH = 170
EDIT_TEXT_PRE_ARM_HEIGHT = 30
EDIT_TEXT_PRE_ARM_OBJECT_NAME = "editText_pre_arm_code"

GROUPBOX_ARM_MODE_TITLE = "Arm Mode"
GROUPBOX_ARM_MODE_LEFT = 10
GROUPBOX_ARM_MODE_TOP = 140
GROUPBOX_ARM_MODE_WIDTH = 280
GROUPBOX_ARM_MODE_HEIGHT = 80
GROUPBOX_ARM_MODE_OBJECT_NAME = "groupBox_arm_mode"

BUTTON_ARMED_MANUAL_TITLE = "Armed Manual"
BUTTON_ARMED_MANUAL_LEFT = 5
BUTTON_ARMED_MANUAL_TOP = 24
BUTTON_ARMED_MANUAL_WIDTH = 130
BUTTON_ARMED_MANUAL_HEIGHT = 45
BUTTON_ARMED_MANUAL_OBJECT_NAME = "pushButton_armed_manual"

BUTTON_AUTO_ENGAGE_TITLE = "Auto Engage"
BUTTON_AUTO_ENGAGE_LEFT = 142
BUTTON_AUTO_ENGAGE_TOP = 24
BUTTON_AUTO_ENGAGE_WIDTH = 130
BUTTON_AUTO_ENGAGE_HEIGHT = 45
BUTTON_AUTO_ENGAGE_OBJECT_NAME = "pushButton_auto_engage"

# Command Panel
GROUPBOX_COMMAND_PANEL_TITLE = "Command Console"
GROUPBOX_COMMAND_PANEL_WIDTH = 300
GROUPBOX_COMMAND_PANEL_HEIGHT = 280
GROUPBOX_COMMAND_PANEL_OBJECT_NAME = "groupBox_action_panel"

FRAME_COMMAND_PANEL = "frame_command_panel"

# Auto engage
GROUPBOX_TARGET_ORDER_WIDTH = 260
GROUPBOX_TARGET_ORDER_HEIGHT = 50

BUTTON_KEY_1_OBJECT_NAME = "pushButton_key_1"
BUTTON_KEY_2_OBJECT_NAME = "pushButton_key_2"
BUTTON_KEY_3_OBJECT_NAME = "pushButton_key_3"
BUTTON_KEY_4_OBJECT_NAME = "pushButton_key_4"
BUTTON_KEY_5_OBJECT_NAME = "pushButton_key_5"
BUTTON_KEY_6_OBJECT_NAME = "pushButton_key_6"
BUTTON_KEY_7_OBJECT_NAME = "pushButton_key_7"
BUTTON_KEY_8_OBJECT_NAME = "pushButton_key_8"
BUTTON_KEY_9_OBJECT_NAME = "pushButton_key_9"
BUTTON_KEY_0_OBJECT_NAME = "pushButton_key_0"
BUTTON_KEY_STOP_OBJECT_NAME = "pushButton_key_stop"
BUTTON_KEY_PLAY_PAUSE_OBJECT_NAME = "pushButton_key_play_pause"
BUTTON_KEY_WIDTH = 70
BUTTON_KEY_HEIGHT = 40

PLAY_PAUSE_ICON_PATH = "./resources/play-and-pause-button.png"
PAUSE_ICON_PATH = "./resources/pause.png"
PLAY_PAUSE_STOP_ICON_SIZE = 30
STOP_ICON_PATH = "./resources/stop-button.png"

GROUPBOX_TARGET_ORDER_TITLE = "Target Order"
GROUPBOX_TARGET_ORDER_OBJECT_NAME = "groupBox_target_order"
EDIT_TEXT_TARGET_ORDER_OBJECT_NAME = "editText_target_order"

# Armed Manual
CHECKBOX_LASER = "Laser enable"
CHECKBOX_CAL = "Calibrate"

MANUAL_DIRECTION_KEY_ICON_SIZE = 65
MANUAL_FIRE_KEY_ICON_WIDTH = 200
MANUAL_FIRE_KEY_ICON_HEIGHT = 65

UP_KEY_ICON_PATH = "./resources/I_Up_key.png"
LEFT_KEY_ICON_PATH = "./resources/J_Left_key.png"
DOWN_KEY_ICON_PATH = "./resources/M_Down_key.png"
RIGHT_KEY_ICON_PATH = "./resources/L_Right_key.png"
FIRE_KEY_ICON_PATH = "./resources/F_fire_key.png"

# Log Panel
NONEDIT_TEXT_LOG_LEFT = 10
NONEDIT_TEXT_LOG_TOP = 750
NONEDIT_TEXT_LOG_WIDTH = 300
NONEDIT_TEXT_LOG_HEIGHT = 105
NONEDIT_TEXT_LOG_OBJECT_NAME = "nonEditText_log"

# Video Panel
GROUPBOX_CAMERA_VIDEO_TITLE = "Camera Video"
GROUPBOX_CAMERA_VIDEO_LEFT = 280
GROUPBOX_CAMERA_VIDEO_TOP = 10
GROUPBOX_CAMERA_VIDEO_WIDTH = 1110
GROUPBOX_CAMERA_VIDEO_HEIGHT = 730
GROUPBOX_CAMERA_VIDEO_OBJECT_NAME = "groupBox_camera_video"

CAMERA_VERTICAL_LAYOUT_WIDGET_LEFT = 10
CAMERA_VERTICAL_LAYOUT_WIDGET_TOP = 20
CAMERA_VERTICAL_LAYOUT_WIDGET_WIDTH = 1100
CAMERA_VERTICAL_LAYOUT_WIDGET_HEIGHT = 690
CAMERA_VERTICAL_LAYOUT_WIDGET_OBJECT_NAME = "verticalLayoutWidget"

CAMERA_VERTICAL_LAYOUTE_OBJECT_NAME = "verticalLayout"

LABEL_CAMERA_VIDEO_OBJECT_NAME = "label_camera_video"

# Algorithm Panel
GROUPBOX_ALGORITHM_TITLE = "Algorithm"
GROUPBOX_ALGORITHM_OBJECT_NAME = "groupBox_algorithm"
GROUPBOX_ALGORITHM_WIDTH = 280
GROUPBOX_ALGORITHM_HEIGHT = 120

BUTTON_ALGO_WIDTH = 110
BUTTON_ALGO_HEIGHT = 60
BUTTON_ALGO_ICON_WIDTH = 20
BUTTON_ALGO_ICON_HEIGHT = 20
BUTTON_OPEN_CV_TITLE = "OpenCV"
BUTTON_TENSOR_FLOW_TITLE = "TensorFlow"
BUTTON_OPEN_CV_ICON_PATH = "./resources/openCV.png"
BUTTON_TENSOR_FLOW_ICON_PATH = "./resources/tensorflow.png"

# Robot Action Panel
GROUPBOX_ROBOT_ACTION_TITLE = "Robot Action"

COMMAND_WIDGET_AUTO = 0
COMMAND_WIDGET_MANUAL = 1

KEY_UP_1 = "up"
KEY_UP_2 = "i"
KEY_DOWN_1 = "down"
KEY_DOWN_2 = "m"
KEY_LEFT_1 = "left"
KEY_LEFT_2 = "j"
KEY_RIGHT_1 = "right"
KEY_RIGHT_2 = "l"
KEY_FIRE_1 = "space"
KEY_FIRE_2 = "f"

MENU_EXIT_DIALOG_TITLE = "Exit Confirmation"
MENU_EXIT_DIALOG_TEXT = "Are you sure you want to exit?"

MENU_ABOUT_DIALOG_TITLE = "About LgClientDisplay"
MENU_ABOUT_DIALOG_TEXT = "LgClientDisplay by NewJeans, Version 1.0\nCopyright (c) 2024"

ALERT_DIALOG_TITLE = "Warning"

SUB_STATE_ARMED = "ARMED"
SUB_STATE_FIRING = "FIRING"
SUB_STATE_LASER_ON = "LASER_ON"
SUB_STATE_LASER_OFF = "LASER_OFF"
SUB_STATE_CALIB_ON = "CALIB_ON"
SUB_STATE_CALIB_OFF = "CALIB_OFF"

# Dialog
DIALOG_TITLE = "Configuration Settings"
GROUP_BOX_OPEN_CV = "OpenCV Config"
GROUP_BOX_TENSOR_FLOW = "TensorFLow Config"
LABLE_OPEN_CV_THRESHOLD = "Threshold:"
LABLE_OPEN_CV_AREA1 = "Area1:"
LABLE_OPEN_CV_AREA2 = "Area2:"
LABLE_TENSOR_FLOW_T1 = "Threshold1:"
LABLE_TENSOR_FLOW_T2 = "Threshold2:"
LABLE_TENSOR_FLOW_DYNAMIC = "Threshold2:"
BUTTON_SET = "Set"
BUTTON_ON = "On"
BUTTON_OFF = "Off"
BUTTON_CV_THRESHOLD_OBJECT_NAME = "cv_threashold"
BUTTON_CV_AREA1_OBJECT_NAME = "cv_area1"
BUTTON_CV_AREA2_OBJECT_NAME = "cv_area2"
BUTTON_TF_T1_OBJECT_NAME = "tf_threshold1"
BUTTON_TF_T2_OBJECT_NAME = "tf_threshold2"
BUTTON_TF_DY_MV_ON_OBJECT_NAME = "tf_dy_mv_on"
BUTTON_TF_DY_MV_OFF_OBJECT_NAME = "tf_dy_mv_off"

# Server Message Prefix
SERVER_MESSAGE_TYPE_TITLE = "[title]"
SERVER_MESSAGE_TYPE_ERROR = "[error]"
SERVER_MESSAGE_TYPE_ALERT = "[alert]"