REMOTE_PORT_NUM = 5000

# Send Type
MT_COMMANDS = 1
MT_TARGET_SEQUENCE = 2
MT_PREARM = 5
MT_STATE_CHANGE_REQ = 7
MT_CALIB_COMMANDS = 8

# Custom
MT_CONFIG = 100

# Receive Type
MT_IMAGE = 3
MT_TEXT = 4
MT_STATE = 6

NETWORK_CONNECTED = 0
NETWORK_DISCONNECTED = 1
NETWORK_CONNECTING = 2