SYSTEM_MODE_UNKNOWN = 0x00
SYSTEM_MODE_SAFE = 0x01
SYSTEM_MODE_PRE_ARM = 0x02
SYSTEM_MODE_AUTO_ENGAGE = 0x04
SYSTEM_MODE_ARMED_MANUAL = 0x08

SYSTEM_MODE_TEXT_UNKNOWN = "Unknown"
SYSTEM_MODE_TEXT_SAFE = "Safe"
SYSTEM_MODE_TEXT_PRE_ARM = "Pre-arm"
SYSTEM_MODE_TEXT_AUTO_ENGAGE = "Auto Engage"
SYSTEM_MODE_TEXT_ARMED_MANUAL = "Armed Manual"

ARMED        = 0x10
FIRING       = 0x20
LASER_ON     = 0x40
CALIB_ON     = 0x80

# Detection algorithm
CMD_USE_TF      = 0x16
CMD_USE_OPENCV  = 0x17
TITLE_OPEN_CV  = "OpenCV"
TITLE_TENSOR_FLOW  = "TensorFlow"

# Pre-Arm, Manual
PAN_LEFT_START = 0x01
PAN_RIGHT_START = 0x02
PAN_UP_START = 0x04
PAN_DOWN_START= 0x08
FIRE_START = 0x10
PAN_LEFT_STOP = 0xFE
PAN_RIGHT_STOP = 0xFD
PAN_UP_STOP = 0xFB
PAN_DOWN_STOP = 0xF7
FIRE_STOP = 0xEF

# Calibration
DEC_X = 0x01
INC_X = 0x02
DEC_Y = 0x04
INC_Y = 0x08

AUTO_ENGAGE_STOP = 0x11
AUTO_ENGAGE_PAUSE = 0x12
AUTO_ENGAGE_RESUME = 0x13

SYSTEM_MODE_LIST = [SYSTEM_MODE_UNKNOWN, SYSTEM_MODE_SAFE, SYSTEM_MODE_PRE_ARM, SYSTEM_MODE_AUTO_ENGAGE, SYSTEM_MODE_ARMED_MANUAL]
SYSTEM_MODE_DICT = {SYSTEM_MODE_UNKNOWN: "Unknown", SYSTEM_MODE_SAFE: "Safe Mode", 
                    SYSTEM_MODE_PRE_ARM: "Pre-Arm Mode", SYSTEM_MODE_AUTO_ENGAGE: "Auto-Engage Mode",
                    SYSTEM_MODE_ARMED_MANUAL: "Armed Manual Mode"}

PRE_ARM_CODE = "12345678"

# Config Type
CONFIG_ID_CV_THRESHOLD = "CV_THRESHOLD"
CONFIG_ID_CV_AREA1 = "CV_AREA1"
CONFIG_ID_CV_AREA2 = "CV_AREA2"
CONFIG_ID_CV_AREA_MIN = "CV_AREA_MIN"
CONFIG_ID_CV_AREA_MAX = "CV_AREA_MAX"
CONFIG_ID_TF_T1 = "TF_THRESHOLD1"
CONFIG_ID_TF_T2 = "TF_THRESHOLD2"
CONFIG_ID_TF_EPSILON = "TF_EPSILON"   
CONFIG_ID_TF_DY_MV = "TF_DY_MV"