SYSTEM_MODE_UNKNOWN = 0
SYSTEM_MODE_SAFE = 0x01
SYSTEM_MODE_PRE_ARM = 0x02
SYSTEM_MODE_AUTO_ENGAGE = 0x04
SYSTEM_MODE_ARMED_MANUAL = 0x08
ARMED = 0x10,
FIRING = 0x20,
LASER_ON = 0x40,
CALIB_ON = 0x80

SYSTEM_MODE_LIST = [SYSTEM_MODE_UNKNOWN, SYSTEM_MODE_SAFE, SYSTEM_MODE_PRE_ARM, SYSTEM_MODE_AUTO_ENGAGE, SYSTEM_MODE_ARMED_MANUAL]
SYSTEM_MODE_DICT = {SYSTEM_MODE_UNKNOWN: "Unknown", SYSTEM_MODE_SAFE: "Safe Mode", 
                    SYSTEM_MODE_PRE_ARM: "Pre-Arm Mode", SYSTEM_MODE_AUTO_ENGAGE: "Auto-Engage Mode",
                    SYSTEM_MODE_ARMED_MANUAL: "Armed Manual Mode"}

NETWORK_CONNECTED = 0
NETWORK_DISCONNECTED = 1
NETWORK_CONNECTING = 2